name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security:
    uses: damoun/.github/.github/workflows/security.yml@main
    permissions:
      security-events: write
      contents: read
      actions: read
